<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>WelcomeAdmin</title>
</head>
<body>
Welcome Admin
<%
String link1 = "employeeSignup.jsp";
out.println("<a href ="+link1+">Register an Employee</a>");
String link = "logout.jsp";
out.println("<a href ="+link+">Logout</a>");
%>
<br>
<br>
<%
String details = request.getParameter("try");
if (details!= null){
	
	out.println(details);
	
}

%>
<br>
<br>
Search/edit customer information 
<form action="AdminSearchCustomer.jsp" method="post">
<pre>
Enter customer: <input type="text" name="searchCustomer">
	<input type="submit" value="Submit">
</pre>
</form>

<br>

See sales for a given month and year
<form action="AdminCheckSales.jsp" method="post">
<pre>
Enter date in form of year/month "0000/00": <input type="text" name="date">
	<input type="submit" value="Submit">
</pre>
</form>

<br>

See the reservation a customer made or reservations a flight has
<form action="AdminReservation.jsp">
Select whether to see reservations from a flight or a customer
  <select name="AdminReservation">
  <option value="1">Flight</option>
  <option value="2">Customer</option>
  </select>
<pre>
Type Flight number or customer username: <input type="text" name="name">
	<input type="submit" value="Submit">
</pre>
</form>

<br>

See revenue generated by a flight, customer, or airline
<form action="AdminRevenue.jsp">
Select what you would like to see the revenue for a
  <select name="AdminRevenue">
    <option value="Flight">Flight</option>
    <option value="Customer">Customer</option>
    <option value="Airline">Airline</option>
  </select>
<pre>
Type Flight number or customer username or Airline ID: <input type="text" name="name">
</pre>
  <input type="submit" value="Submit">
</form>

<br>

View Customer that generated most revenue:
<form action="AdminMostRevenueByCustomer.jsp">
<pre>
  <input type="submit" value="Check">
</pre>
</form>

<br>

View top 3 most active flights:
<form action="AdminCheckActiveFlights.jsp" method="post">
<pre>
	<input type="submit" value="Check">
</pre>
</form>

<br>

See all flights in an airport
<form action="AdminCheckFlightsAtAirport.jsp" method="post">
<pre>
Enter AirportID: <input type="text" name="airport">
	<input type="submit" value="Submit">
</pre>
</form>

</body>
</html>